### ISSUE TITLE
Any way to pause and resume the bruteforce?

### ISSUE THREAD

**Issue by Khizary** [programminghoch10/huawei-honor-bootloader-bruteforce#4]
I was hoping I could perform the bruteforce at nights since my device is also kind of a primary daily driver. Can it work? Please tell me how to do it or please add that feature. Thanks in advance.

**Comment by titanx980ti** [comment]
You can pause using , just by unplugging the device from the computer , but in order to resume , you will be needing another computer to resume the code by using the following command adb reboot bootloader , then once your phone is in bootloader mode , just remove and connect back to the main computer , where the python script is active , then it will resume automatically , if you have closed the python script , then you will have to find a file ( unlock_code.txt ) which is in the main directory , copy the oem code and head back to unlock.py script , right click on edit and paste it on aloem code start (100000000000000) this number , replace it with yours 123456789012345 ! , done , now save the file in notepad and enter the same imei and continue :)

**Comment by Khizary** [comment]
ProgrammingHoch10 said it was random numbers so by setting the min value, I would be skipping combinations below that number right? I was thinking maybe storing the variables in a file or something.

**Comment by titanx980ti** [comment]
They are the values which are based on some calculations with respect to your imei code , u can save the number and reuse it later

**Comment by programminghoch10** [comment]
You guys are mixing things together!
First of addressing the original question: You can pause the process just as @titanx980ti explained either by unplugging the device or by killing the process and copying the oemcode before restarting.
But this only applies to the normal algorithm based variant of the code!

@ImKhizy you are probably referring to my random edition.
As this algorithm probably wasn't working anyways, I figured one might as well try random codes.
on the branch `random` of this repository, you will find a version which will try entirely random codes.
As they are random, there is no start and end, so you dont have to do anything with saving progress and such.
Pausing is also not needed here.

I can't tell you which is more probable to work, decide yourself which version is more worth your time.

One more quick note: When using linux on the bruteforce machine, you can use the supplied auto reboot script and start it in parallel to the bruteforce script. This script will automatically reboot your device into bootloader mode when it finds a connected device. This means you can actually let the script run, unplug your device when you want to use it and just plug it in again.

Even more notes: While bruteforcing your battery might not be charging or even discharging! this may cause your battery health to drop and also you may not have a charged battery on the morning.
Also testing on your daily driver might not be a good idea as a factory reset (all data wiped) is issued on unlock.
